[window]
padding = { x = 10, y = 10 }
decorations = "None"

[font]
normal = { family = "Noto Sans Mono", style = "Regular" }
size = 12

[keyboard]  # docs: ‹https://alacritty.org/config-alacritty.html#keyboard› 
bindings = [
    { key = "i",  mods = "Alt", action = "ToggleViMode" },
    { key = "h", mods = "Alt", chars = "emacs -nw . \r && clear"}, 
    { key = "e", mods = "Alt", chars = "emacs -nw ~/Documents \r && clear"}, 
    { key = "o", mode = "Vi|~Search", action = "Open" },
]
